### PR TITLE
Use -- delimeter for a modifier by Harry Roberts

### PR DESCRIPTION
**Pull request by varya**
Changes from PR #47 back here.

### CODE REVIEW

**Comment by varya** [comment]
For some reason `levels/pages/building/building.jade` still exists in the repo. Did you remove the link only?

**Comment by iamstarkov** [comment]
I dont clear remember. prob I removed links and remove building from build step

**Comment by iamstarkov** [comment]
lgtm

**Comment by floatdrop** [comment]
:+1:

**Comment by iamstarkov** [comment]
btw, should we have a note about standard notation?

**Comment by varya** [comment]
Can update tomorrow

**Comment by iamstarkov** [comment]
I think we can merge it now, and add note about standart notation tomorrow

**Pull request merged**
