### PR TITLE
Added Wimdu to the consumers list

### PR DESCRIPTION
**Pull request by lukaszklis**

### CODE REVIEW

**Comment by iamstarkov** [comment]
looks good for me 👍

**Comment by iamstarkov** [comment]
it’s your logo, but i’m going to ask, maybe you want to trim logo, before merge

**Comment by lukaszklis** [comment]
@iamstarkov I can get rid of the extra space from the top and bottom, however then `:hover` looks weird comparing to the other ones. I've processed the file via ImageOptim already.

**Comment by iamstarkov** [comment]
if you are saying that it looks weird in my way, then it looks better in your way. okie

**Comment by iamstarkov** [comment]
published

**Pull request merged**
